const viewAllSkin = [{
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13516546-2844930071318699.jpg",
        name: "SkinCeuticals Phyto A+ Brightening Treatment 3 oz",
        price: 105,
        product_type: "Treatment",
        Description: "Phyto A+ Brightening Treatment, an oil-free, lightweight moisturizer with a gel-creme texture targets dullness, redness, and excess oil production even on sensitive skin. Specially formulated with 3% azelaic acid to target clogged pores, making it the perfect complement for oily and blemish-prone skin.",
        Ingredients: "Aqua / Water / Eau, Glycerin, Isononyl Isononanoate, Propylene Glycol, Azelaic Acid, Niacinamide, Squalane, Alpha-Arbutin, Ammonium Polyacryloyldimethyl Taurate, Hydrogenated Polyisobutene, Silica Silylate, Hydroxyacetophenone, Sodium Hyaluronate, Caprylyl Glycol, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Sodium Hydroxide, Olea Europaea Leaf Extract / Olive Leaf Extract, Parfum / Fragrance, Butylene Glycol, Rosmarinus Officinalis Leaf Extract / Rosemary Leaf Extract, Citrus Grandis Fruit Extract / Grapefruit Fruit Extract, Sodium Benzoate, Cucumis Sativus Fruit Extract / Cucumber Fruit Extract, Sorbitan Isostearate, Polysorbate 60, Benzyl Benzoate, Thymus Vulgaris Flower/Leaf Extract - Thyme Flower/Leaf Extract, Lactic Acid, Benzyl Alcohol, Alpha-Isomethyl Ionone, Linalool, Potassium Sorbate, Citronellol, Morus Alba Root Extract, Ci 19140 / Yellow 5, Ci 42090 / Blue 1, Tocopherol",
        Brand: "SkinCeuticals",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13305187-1604931097281379.jpg",
        name: "Sulwhasoo Concentrated Ginseng Renewing Water 125ml",
        price: 82,
        product_type: "moisture",
        Description: "An anti-aging water formulated with precious steamed ginseng water concentrate to replenish dry skin with rich moisture. What it does: It enhances the appearance of resilience in your skin. Ginseng water, the ingredient that helps provide moisture and appearance of firmness to skin, is condensed into steamed ginseng water concentrate, a precious formula acquired through Sulwhasoo's original technology. Steamed ginseng water concentrate makes the skin feel firm and resilient by delivering moisture and nourishment to dry, flaky skin.",
        Ingredients: "Water / Aqua / Eau, Glycerin, Butylene Glycol, Glycereth-26, Alcohol, Betaine, Panax Ginseng Root Water, Glycerylpolymethacrylate,Bis-Peg-18 Methyl Ether Dimethyl Silane, Propanediol, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Tauratecopolymer, Peg-60 Hydrogenated Castor Oil, Caprylic/Capric Triglyceride, Behenyl Alcohol, Polyglyceryl-10Pentastearate, Glyceryl Caprylate, Fragrance / Parfum, Cetearyl Alcohol, Acrylates/C10-30 Alkyl Acrylatecrosspolymer, Tromethamine, Methoxy Peg-114/Polyepsilon Caprolactone, Disodium Edta, Xanthan Gum,Ethylhexylglycerin, 1,2-Hexanediol, Adenosine, Sodium Stearoyl Lactylate, Honey / Mel / Miel, Cetearyl Glucoside,Beta-Glucan, Lilium Candidum Bulb Extract, Rehmannia Glutinosa Root Extract, Paeonia Albiflora Root Extract,Nelumbo Nucifera Flower Extract, Polygonatum Officinale Rhizome/Root Extract, Sorbitan Isostearate,Polysorbate 60, Hydrolyzed Ginseng Saponins, Linalool, Hydrogenated Lecithin, Phenoxyethanol, Caprylyl Glycol,Dextrin, Theobroma Cacao (Cocoa) Extract, Benzyl Benzoate, Potassium Hydroxide, Acetic Acid, Bht, Tocopherol",
        Brand: "Sulwhasoo",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12810684-1104840720634844.jpg",
        name: "Medik8 Advanced Night Ceramide Cream 48g",
        price: 69,
        product_type: "Serum ",
        Description: "This is Medik8's signature night cream and the perfect partner to follow a vitamin A (retinoid) serum in the evening. Infused with a multi-blend of ceramides in an optimized ratio to support the skin's surface and improve the look of firmness. Also featuring a multi-peptide complex and fruit-derived antioxidants, the fast-absorbing yet rich and nourishing cream melts on application creating a sumptuous cocoon of hydration while you sleep. Designed to be used after vitamin A, the formula works perfectly after retinoid serums to moisturize skin, leaving the texture of complexion visibly smooth, supple and nourished.",
        Ingredients: "Water, Squalane, Caprylic/Capric Triglyceride, Dimethicone, Glycerin, Stearic Acid, Propylene Glycol, Phytosterols, C12-16 Alcohols, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Cetearyl Alcohol, Palmitic Acid, Ceramide NP, Cetearyl Olivate, Linoleic Acid, Behenyl Alcohol, Hydrogenated Lecithin, Tocopheryl Acetate, Sorbitan Olivate, Phenoxyethanol, Benzyl Alcohol, Amelanchier Alnifolia Fruit Extract, Ethylhexylglycerin, Acetyl Glucosamine, Citric Acid, Sorbitol, Rosmarinus Officinalis (Rosemary) Leaf Oil, Citrus Aurantium Amara (Bitter Orange) Flower Oil, Lavandula Angustifolia (Lavender) Oil, Citrus Aurantium Dulcis (Orange) Peel Oil, Hylocereus Undatus Fruit Extract, Dehydroacetic Acid, Tremella Fuciformis (Mushroom) Extract, Sodium Lauroyl Lactylate, Anthemis Nobilis Flower Oil, Pogostemon Cablin Leaf Oil, Vetiveria Zizanoides Root Oil, Ascorbic Acid, Disodium EDTA Ceteareth-25, Phytosphingosine, Cholesterol, Xanthan Gum, Carbomer, Cetyl Alcohol, Behenic Acid, Ceramide NS, Ferric Hexapeptide-35, Ceramide EOP, Ceramide EOS, Caprooyl Phytosphingosine, Caprooyl Sphingosine, Ascorbyl Palmitate, Tocopherol, Geraniol, Limonene, Linalool",
        Brand: "Medik8",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13506154-1914930092074211.jpg",
        name: "MZ Skin Hyaluronic Acid Hydrating Serum 30ml",
        price: 165,
        product_type: "Serum ",
        Description: "A lightweight Hyaluronic Acid Serum delivering long-lasting hydration and plumping for all skin types. 5 powerhouse actives instantly increase moisture while helping to soothe and soften the skin. Skin appears hydrated, calm, and dewy.",
        Ingredients: "Water (Aqua), Propanediol, Panthenol, Glycerin, Pyrus Malus (Apple) Fruit Extract, Sodium Polyacryloyldimethyl Taurate, Ethylhexylglycerin, Gluconolactone, Tremella Fuciformis (Mushroom) Extract, Potassium Sorbate, Pentylene Glycol, Sodium Benzoate, Sodium Phytate, Ganoderma Lucidum (Mushroom) Extract, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Citric Acid, Biosaccharide Gum-1, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Sodium Levulinate, Calcium Gluconate, Glyceryl Caprylate, Hydrolyzed Sodium Hyaluronate, Sodium Anisate.",
        Brand: "MZ Skin",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13468234-5434916661811767.jpg",
        name: "Decorté Liposome Advanced Repair Serum (Various Sizes)",
        price: 75,
        product_type: "Serum ",
        Description: "Powered by Liposome Technology™, Decorté present an ultra-lightweight serum that offers time-released hydration. Made up of phospholipids, the capsules enforces a protective barrier over skin that locks in hydration and assists the natural repair process.",
        Ingredients: "Water/Aqua/Eau, Butylene Glycol, Glycerin, Hydrogenated Lecithin, Dipropylene Glycol, Acetyl Glutamine, Betula Platyphylla Japonica Juice, Bifida Ferment Lysate, Ceramide Ng, Endomyces Ferment Filtrate, Hydrolyzed Hyaluronic Acid, Hydrolyzed Yeast Protein, Hydroxyproline, Rhodomyrtus Tomentosa Fruit Extract, Serine, Sodium Pca, Tocopherol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Disodium Succinate, Ectoin, Glycine Soja (Soybean) Sterols, Phytosterols, Sodium Hydroxide, Succinic Acid, Xanthan Gum, Phenoxyethanol, Sodium Benzoate, Fragrance (Parfum).",
        Brand: "Decorté",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289609-1174892770940184.jpg",
        name: "SkinCeuticals C E Ferulic with 15% L-Ascorbic Acid Vitamin C Serum 30ml",
        price: 166,
        product_type: "Serum ",
        Description: "Experience advanced environmental protection with SkinCeuticals C E Ferulic; a potent Vitamin C serum that delivers visible anti-aging benefits. Free from parabens, the formula is gentle yet effective and is suitable for normal, dry and even sensitive skin types. The serum delivers an array of enviable benefits that last over 72 hours. Simply smooth 4-5 drops of the fast-absorbed solution over the face, neck and décolletage.",
        Ingredients: "Water, Ethoxydiglycol, L-Ascorbic Acid, Propylene Glycol, Glycerin, Laureth-23, Alpha Tocopherol, Phenoxyethanol, Triethanolamine, Ferulic Acid, Panthenol, Sodium Hyaluronate.",
        Brand: "SkinCeuticals",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/10915787-1224882139201778.jpg",
        name: "Sunday Riley Good Genes All-In-One Lactic Acid Treatment 1oz",
        price: 85,
        product_type: "Treatment ",
        Description: "Reveal a refreshed complexion with the Sunday Riley Good Genes Treatment; a clarifying formula that provides an instant and long-lasting boost for fatigued skin in need of a pick-me-up.",
        Ingredients: "Opuntia Tuna Fruit (Prickly Pear) Extract, Agave Tequilana Leaf (Blue Agave) Extract, Cypripedium Pubescens (Lady's Slipper Orchid) Extract, Opuntia Vulgaris (Cactus) Extract, Aloe Barbadensis Leaf Extract & Saccharomyses Cerevisiae (Yeast) Extract, Lactic Acid, Caprylic/Capric Triglyceride, Butylene Glycol, Squalane, Cyclomethicone, Dimethicone, Ppg-12/Smdi Copolymer, Stearic Acid, Cetearyl Alcohol And Ceteareth20, Glyceryl Stearate And Peg-100 Stearate, Arnica Montana (Flower) Extract, Peg-75 Meadowfoam Oil, Glycyrrhiza Glabra (Licorice) Root Extract, Cymbopogon Schoenanthus (Lemongrass) Oil, Triethanolamine, Xantham Gum, Phenoxyethanol, Steareth-20, Dmdm Hydantoin.",
        Brand: "Sunday Riley",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11388132-1094867645304493.jpg",
        name: "Dermalogica Daily Superfoliant 2oz",
        price: 62,
        product_type: "Treatment",
        Description: "Improve skin tone and texture with the Dermalogica Daily Superfoliant™; a powder exfoliant that delivers anti-aging, anti-pollution and skin-resurfacing benefits",
        Ingredients: "Microcrystalline Cellulose, Sodium Bicarbonate, Sodium Cocoyl Glutamate, Sodium Myristoyl Glutamate, Malic Acid, Sodium Methyl Cocoyl Taurate, Charcoal Powder, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Maltodextrin, Silica, Magnesium Oxide, Oryza Sativa (Rice) Bran Extract, Polymethylsilsesquioxane, Sapindus Trifoliatus Fruit Extract, Niacinamide, Citrus Aurantium Amara (Bitter Orange) Peel Oil, Zingiber Of cinale (Ginger) Root Extract, Lavandula Angustifolia (Lavender) Oil, Lavandula Hybrida Oil, Camellia Sinensis Leaf, Kappaphycus Alvarezii Extract, Caesalpinia Spinosa Fruit Pod Extract, Citrus Limon (Lemon) Peel Oil, Rosmarinus Of cinalis (Rosemary) Leaf Oil, Salvia Of cinalis (Sage) Oil, Subtilisin, Lipase, Papain, Lactic Acid, Oryza Sativa (Rice) Starch, Sodium Chloride, Sodium Dehydroacetate, Xanthan Gum, Water/Aqua/Eau, Coconut Acid, Calcium Lactate, Capryloyl Glycine, Undecylenoyl Glycine, Cetrimonium Chloride, Limonene, Linalool.",
        Brand: "Dermalogica",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370303-1394876993507764.jpg",
        name: "EltaMD UV Clear Broad-Spectrum SPF46",
        price: 37,
        product_type: "cream",
        Description: "With EltaMD UV Clear Broad-Spectrum SPF 46, you need not worry about your sensitive skin anymore. As the 2010 Winner of Elle Genius Award for Skin, EltaMD UV Clear Broad-Spectrum SPF 46 offers not only UVA/UVB protection, but also treatment for skin discoloration and acne. Its oil-free, light texture goes on smooth, leaving behind no residue on the skin. This product maintains skin health by freeing skin of fatty acid levels and reducing redness. This oil-free, non-comedogenic formula can be worn with or without makeup.",
        Ingredients: "Zinc oxide: Natural mineral compound that works as a sunscreen agent by reflecting and scattering UVA and UVB rays.Niacinamide (vitamin B3): Anti-inflammatory that reduces redness and enhances the appearance of dry or damaged skin and restores suppleness.Sodium hyaluronate (Hyaluronic Acid): Humectant that attracts and retains moisture, improving skin feel and restores suppleness.Tocopheryl acetate (vitamin E): Antioxidant that reduces free radicals to help diminish the visible signs of aging.",
        Brand: "EltaMD",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289630-1114892772061416.jpg",
        name: "SkinCeuticals Phyto+ 30ml",
        price: 87,
        product_type: "cream",
        Description: "The SkinCeuticals Phyto+ is a botanically-derived corrective treatment with soothing, restorative properties, working to dramatically improve the appearance of discoloration without causing irritation.The refreshing gel formula is based upon Hyaluronic Acid, providing intensive hydrating benefits, while extracts of naturally sourced Arbutin and Kojic Acid work to lift away the look of dark spots and hyperpigmentation for a more even and unified tone. Extracts of Cucumber and Thyme promote feelings of calm and alleviate discomfort, leaving the complexion feeling revitalized and fresh. Suitable for all skin types.",
        Ingredients: "Aqua / Water / Eau, Glycerin, Propylene Glycol, Kojic Acid, Arbutin, Polysorbate 80, Phenoxyethanol, Citrus Grandis Extract / Grapefruit Fruit Extract, Parfum / Fragrance, Sodium Hyaluronate, Arctostaphylos Uva Ursi / Arctostaphylos Uva Ursi Leaf Extract, Thymus Vulgaris Extract / Thyme Extract, Cucumis Sativus (Cucumber) Seed Extract, Hydroxyethylcellulose, Ci 19140 / Yellow 5, Ci 42090 / Blue 1.",
        Brand: "SkinCeuticals",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11054488-6294867924186974.jpg",
        name: "First Aid Beauty Ultra Repair Cream (6 oz.)",
        price: 38,
        product_type: "Cream ",
        Description: "FAB Ultra Repair Cream is a thick, rich, emollient product that hydrates deep down with exceptional penetration. With the help of Colloidal Oatmeal, Shea Butter, soothing Eucalyptus Oil and ceramides, FAB Ultra Repair Cream provides immediate relief and visible improvement for distressed skin. FAB Antioxidant Booster is there to defend skin from free radical damage. Ultra Repair Cream can be used all over the body and on the face.",
        Ingredients: "Colloidal Oatmeal, Water, Stearic Acid, Glycerin, C12-15 Alkyl Benzoate, Caprylic/Capric Triglyceride, Glyceryl Stearate, Glyceryl Stearate SE, Cetearyl Alcohol, Caprylyl Glycol, Phenoxyethanol, Butyrospermum Parkii (Shea Butter), Squalane, Allantoin, Sodium Hydroxide, Dimethicone, Xanthum Gum, Disodium EDTA, Chrysanthemum Parthenium (Feverfew) Extract, Camellia Sinensis Leaf Extract, Butylene Glycol, Glycyrrhiza Glabra (Licorice) Root Extract, Eucalyptus Globulus, Ceramide 3.",
        Brand: "First Aid Beauty",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13507090-6724918929137595.jpg",
        name: "Glo Skin Beauty HA-Revive Hyaluronic Hydrator 50ml",
        price: 78,
        product_type: "Moisture",
        Description: "Powered by age-defying actives, HA-Revive Hyaluronic Hydrator is a next-generation treatment moisturizer formulated to target dry, dehydrated, and dull skin. Delivering hyper-hydration deep within thanks to its micro-molecule hyaluronic acid infusion, it restores skin’s suppleness and plumpness. Soothing while anti-aging, phyto-retinol reduces the appearance of fine lines and wrinkles, while plant stem cell antioxidants protect and restore skin’s natural radiance.",
        Ingredients: "A plant-based alternative to vitamin A (retinol), it has similar smoothing, refining, and elasticity-boosting benefits, with a more gentle sensitive skin-friendly approach.",
        Brand: "Glo Skin Beauty",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13507090-6724918929137595.jpg",
        name: "Glo Skin Beauty HA-Revive Hyaluronic Hydrator 50ml",
        price: 78,
        product_type: "Moisture",
        Description: "Formerly Phyto-Active Light Moisture. This active age-defying moisturizer restores skin’s suppleness and vitality, with hyaluronic acid and plant stem cells delivering weightless hydration for a plumped, smoothed glow.",
        Ingredients: "A plant-based alternative to vitamin A (retinol), it has similar smoothing, refining, and elasticity-boosting benefits, with a more gentle sensitive skin-friendly approa",
        Brand: "Glo Skin Beauty",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12053028-5704882135372731.jpg",
        name: "Sunday Riley C.E.O. Glow Vitamin C + Turmeric Face Oil 35ml (Worth $94)",
        price: 80,
        product_type: "Oil ",
        Description: "Reignite skin's radiance with the Sunday Riley C.E.O. Glow Vitamin C + Turmeric Face Oil, a glow-giving elixir that uses Advanced Vitamin C (THD Ascorbate) blended in a base of cold-pressed Red Raspberry and Evening Primrose Seed Oils for instant vibrancy.Absorbing rapidly into skin, the face oil works to brighten and hydrate the look of skin to recharge your natural radiance. Promoting a healthy-looking luster, it contains Golden Turmeric extract for its antioxidant-rich composition, calming properties and ability to improve the look of skin evenness. Delivers instant glow and antioxidant protection.",
        Ingredients: "Water/Eau/Aqua, Tetrahexyldecyl Ascorbate, Squalane, Polyglyceryl-6 Distearate, Peg-8 Beeswax, Limonene, Citrus Sinesis (Sweet Orange) Oil, Citrus Tangerina Peel Oil, Glycine Soja Sterols, Ppg-12/Smdi Copolymer, Sodium Phytate, Tocopherol, Phenoxyethanol, Acetamidoethoxyethanol, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Jojoba Esters, Glycolic Acid, Caprylyl Glycol, Cetyl Alcohol, Polyglyceryl-3 Beeswax, Chlorphenesin Glycerin, Polysorbate 60, Sorbitan Isostearate, Saccharide Isomerate, Linalool.",
        Brand: "Sunday Riley",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13414778-1464931103508845.jpg",
        name: "Sulwhasoo Concentrated Ginseng Renewing Cream Mask 0.25 oz",
        price: "120",
        product_type: "Cream ",
        Description: "",
        Ingredients: "",
        Brand: "Sulwhasoo ",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/960/960/11370309-1794866342158184.jpg",
        name: "EltaMD UV Aero Broad-Spectrum SPF45",
        price: 34,
        product_type: "sunscreen",
        Description: "Elta MD UV Aero Broad-Spectrum SPF 45 is an oil-free, water-resistant, spray-on sunscreen that uses transparent zinc oxide to shield the skin from damage. It sprays on white, so you can see where to apply, then dries clear. The fast and convenient application method makes it ideal for the entire family.",
        Ingredients: "Butylene Glycol, Capryloyl Glycine, Cyclopentasiloxane, Dimethicone, Dimethicone/PEG-10/15 Crosspolymer, Dimethicone/Vinyl Dimethicone Crosspolymer, Isobutane, Lauryl PEG-9 Polymethylsiloxyethyl Dimethicone, Phenoxyethanol, Propane, Purified Water, Sodium Chloride, Triethoxycaprylylsilane, Undecylenoyl Glycine",
        Brand: "EltaMD",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11724091-6114853912559885.jpg",
        name: "BABOR Ampoule Hydra Plus 7 x 2ml",
        price: "29",
        product_type: "Cream ",
        Description: "Revive dehydrated skin with an intensive moisture boost with the Hydra Plus Ampoules from Germany’s leading professional skincare label, BABOR; a set of seven individually sealed ampoules containing an advanced active concentrate to replenish moisture levels. Innovative and highly effective, each serum-based ampoule contains a complex balance of Hyaluronic Acid and a plant-based Polymer Moisturizer, which work in synergy to deliver essential hydration and lock in moisture with a protective film. Skin feels plump, fresh and instantly invigorated with a restored vitality",
        Ingredients: "Aqua, Glycerin, Saccharide Isomerate, C12-15 Pareth-12, Sodium Pca, Phenoxyethanol, Peg-7 Glyceryl Cocoate, Parfum, Ethylhexylglycerin, Potassium Sorbate, Citric Acid, Sodium Hyaluronate, Sodium Citrate, Disodium EDTA.",
        Brand: "BABOR",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11290635-1804892767902966.jpg",
        name: "SkinCeuticals Triple Lipid Restore 2:4:2",
        price: 130,
        product_type: "Treatment",
        Description: "Treat your skin to the smoothing properties of SkinCeuticals Triple Lipid Restore 2:4:2, an anti-aging cream that improves the texture of skin while directly addressing age-related lipid loss. barrier while supporting natural self-repair. Lightweight and fast-absorbing, the cream melts effortlessly into skin, effectively improving texture, fullness and the appearance of pores. Expect a brighter, more even-looking canvas that feels smooth, comforted and youthful. Enriched with an essential oil blend of Lavender, Rosemary, and Peppermint Oil for a cooling, comforting effect.In an 8-week study, Triple Lipid Restore 2:4:2 significantly improved the appearance of key visible signs of accelerated aging.1 • 66% improvement in smoothness • 35% improvement in laxity • 20% improvement in evenness • 26% improvement in radiance • 44% improvement in pore appearance In a reproduction, helping defend against environmental Essential Oils: packed with antioxidants to fight free-radical damage that is responsible for signs of aging",
        Ingredients: "Aqua/Water/Eau, Dimethicone, Hydrogenated Polyisobutene, Glycerin, Cholesterol, C12-15 Alkyl Benzoate, Ceramide 3, Helianthus Annuus Seed Oil Unsaponifiables/Sunflower Seed Oil Unsaponifiables, Bis-Peg-18 Methyl Ether Dimethyl Silane, Sodium Polyacrylate, Peg-10 Dimethicone, Nylon-12, Lauryl Peg-9 Polydimethylsiloxyethyl Dimethicone, Dimethicone/Peg-10/15 Crosspolymer, Phenoxyethanol, Disteardimonium Hectorite, Hydroxyethylpiperazine Ethane Sulfonic Acid, Ammonium Polyacryloyldimethyl Taurate, Chlorphenesin, Caprylyl Glycol, Peg/Ppg-18/18 Dimethicone, Propylene Carbonate, Disodium Edta, Acrylonitrile/Methyl Methacrylate/Vinylidene Chloride Copolymer, Adenosine, Dipropylene Glycol, Lavandula Angustifolia Oil/Lavender Oil, Rosmarinus Officinalis Leaf Oil/Rosemary Leaf Oil, T-Butyl Alcohol, Mentha Piperita Oil/Peppermint Oil, Sodium Citrate, Linalool, Isobutane, Ceramide Eop, Bht, Tocopherol, Limonene, D182888/1",
        Brand: "SkinCeuticals",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/13206070-6364898325936423.jpg",
        name: "Omorovicza Evening CBD Facial Set",
        price: 281,
        product_type: "Treatment",
        Description: "The Omorovicza Evening CBD Facial Set provides the perfect wind-down skincare routine, featuring four staple products to cleanse, nourish and prep your complexion before sleep",
        Ingredients: "Rejuvenating Night Cream: Aqua (Hungarian Thermal Water), Glycerin, Butyrospermum Parkii (Shea Butter), Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Caprylic/Capric Triglyceride, Cetearyl Ethylhexanoate, Prunus Domestica Seed Extract, Cetearyl Olivate, Stearyl Heptanoate, Sorbitan Olivate, Cetearyl Alcohol, Hydrolyzed Hazelnut Protein, Saccharomyces (Hungarian Thermal Water) Ferment Extract, Cera Alba (Beeswax), Phenoxyethanol, Mannitol, Sodium Lactate, Malpighia Punicifolia (Acerola) Fruit Extract, Prunus Armeniaca (Apricot) Kernel Oil, Xanthan Gum, Disodium EDTA, Pyrus Malus (Apple) Fruit Extract, Helianthus Annuus (Sunflower) Seed Oil, Tocopherol, Ethylhexylglycerin, Parfum (Fragrance), Phospholipids, Chlorella Vulgaris/ Lupinus Albus Protein Ferment, Pectin, Yeast Extract, Linalool, Geraniol, Potassium Sorbate, Beta-Carotene, Daucus Carota Sativa (Carrot) Root Extract, Daucus Carota Sativa (Carrot) Seed Oil, Cinnamyl Alcohol, Ascorbyl Palmitate.",
        Brand: "Omorovicza",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp/productimg/960/960/11429066-1744528379596254.jpg",
        name: "La Roche-Posay Toleriane Hydrating Gentle Cleanser (Various Sizes)",
        price: 11,
        product_type: "Cleanser",
        Description: "",
        Ingredients: "",
        Brand: "La Roche-Posay",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/960/960/12852429-5104876441475610.jpg",
        name: "EltaMD UV Glow Broad-Spectrum SPF36+ Tinted Serum 1.7 oz",
        price: 38,
        product_type: "Serum",
        Description: "Rich in powerhouse antioxidants like high-purity niacinamide and ergothioneine, it brightens skin, protects against daily skin-aging aggressors, and promotes the appearance of healthy, glowing skin. Niacinamide also helps improve and even skin tone—perfect for anyone with skin prone to discoloration. Meanwhile, skin-brightening mineral mica instantly creates a dewy, luminous finish.",
        Ingredients: "Water, Coco-Caprylate/Caprate, Niacinamide, Isopropyl Myristate, Polyglyceryl-3 Diisostearate, Ethyl Macadamiate, Mica, Glycerin, Propanediol, Cetearyl Nonanoate, Capryloyl Glycerin/Sebacic Acid Copolymer, Undecane, Caprylic/Capric Triglyceride, Tridecane, Polyglyceryl-3 Polyricinoleate, Disteardimonium Hectorite, Phenoxyethanol, Octyldodecyl Oleate, Sodium Chloride, Magnesium Sulfate, Tocopheryl Acetate, Isostearic Acid, Cocos Nucifera (Coconut) Fruit Extract, Xanthan Gum, Bisabolol, Silica, Sodium Hyaluronate, Aloe Barbadensis Leaf Juice, Lactic Acid, Zingiber Officinale (Ginger) Root Extract, Ergothioneine, Iron Oxides.",
        Brand: "EltaMD",
    },
    {
        image_link: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11986270-7564871574685569.jpg",
        name: "NuFACE FIX Line Smoothing Device and Serum",
        price: 149,
        product_type: "Serum",
        Description: "A powerful Microcurrent Skincare duo that instantly targets the appearance of fine lines and wrinkles around the eyes, lips, and forehead within 3 minutes",
        Ingredients: "Water/Aqua/Eau, Propanediol, Glycerin, Ethylene/Acrylic Acid Copolymer, Palmitoyl Hexapeptide-52, Palmitoyl Heptapeptide-18, N-Prolyl Palmitoyl Tripeptide-56 Acetate, Olivine Extract, Hydrolyzed Hyaluronic Acid, Betaine, Tremella Fuciformis Sporocarp Extract, Lactic Acid/Glycolic Acid Copolymer, Pentylene Glycol, Carbomer, Xanthan Gum, Polyvinyl Alcohol, Poloxamer 338, Tocopherol, Sodium Citrate, Sodium Hydroxide, Silica, Mica, Caprylyl Glycol, Potassium Sorbate, Glyceryl Caprylate, Ethylhexylglycerin, Phenoxyethanol, Phenylpropanol, Sodium Metabisulfite, Bismuth Oxychloride (CI 77163), Iron Oxides (CI 77491, CI 77492)For external use only. Discontinue use if irritation develops.",
        Brand: "NuFACE",
    },
];